### ISSUE TITLE
Set the directory for secrets 

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-manage-service#110]
The manage-service needs a password. This has to be in the folder ./secrets/ in the same folder then pwd. It is currently not possible to run the binary from another place.

Could you add an attribute to set the secret folder?

For example, if you start the manage-server in the main repo (with all the subrepos), it should be possible to do something like this:

```
cd openslides-manage-service
go build ./cmd/openslides
./openslides --secrets ../docker/secrets foobar
```

**Comment by normanjaeckel** [comment]
Hm. Please describe a usecase. For the password, the manage tool uses, you already have a command line flag. For the secrets given to docker they have to lay next to the docker-compose.yml. So what should this new flag do? If you like you can explain it to me via phone call.

**Comment by ostcar** [comment]
As discussed. This already works.
