### ISSUE TITLE
Can we remove *_USER_FILE env vars.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#116]
See email discussion: The question is whether the `*_USER_FILE` env vars are really necessary. In my opinion the secret is only the password. The username of the postgres db should be given in cleartext and not as secret. The env vars would be `DATASTORE_DATABASE_USER`, `MEDIA_DATABASE_USER` and `VOTE_DATABASE_USER`.

**Comment by gsiv** [comment]
As far as access security is concerned, you are right that only the password is a secret.  However, the user name, while not a secret per se, may still constitute PII that maybe should not be shared without a good reason with *all other* services as is currently the case with regular variables.

When I suggested to make the user name a secret, I imagined that both the user name and the password would be contained in a single secret file like it was done in OpenSlides 3.  It's a simple and clear method for avoiding some unnecessary data sharing between services and an improvement that comes at almost no cost.

If that is not an option and the user name must instead be managed as a separate secret file, with all the extra configuration overhead such as those variables that go along with it these days, then I agree that it is overkill.

**Comment by ostcar** [comment]
I would like to give the username as an open environment variable to the services.

I think this is easier

**Comment by jsangmeister** [comment]
I agree with @ostcar and already went ahead and changed it in the datastore in https://github.com/OpenSlides/openslides-datastore-service/pull/164 (because I did not see this issue).

**Comment by peb-adr** [comment]
user file secrets have been removed in #118.
I'll close this.
