### ISSUE TITLE
Don't let redis use persistant storage

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#119]
@ostcar Can you please help and let me know how to change the docker-compose.yml redis section so that redis does not use a persistent storage. Thanks.

**Comment by ostcar** [comment]
First, you have to read the documentation :)

https://hub.docker.com/_/redis
https://redis.io/topics/persistence
https://raw.githubusercontent.com/redis/redis/6.2/redis.conf
https://redis.io/commands/SHUTDOWN

Here is what you don't want: `docker run  --network host --name tredis  redis`

In another terminal call `redis-cli`, and then:
```
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> set foo bar
OK
```

Then stop the redis container and restart it with: `docker start tredis`

In another terminal call `redis-cli`again and call:
```
127.0.0.1:6379> keys *
1) "foo"
127.0.0.1:6379> get foo
"bar"
```

As you can see the key is still there and had to be saved on disk.

So lets do what you want:

(first, delete the old container `docker stop tredis` and `docker container rm tredis`

Start the container without any persistence: `docker run  --network host --name tredis  redis --save ""`

Add a key in another terminal as before and afterwards stop the container. Then restart it with `docker start tredis`

In another terminal, call `redis-cli` and call:

```
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> get foo
(nil)
```

As you can see, no data where loaded on startup. So all you have to do is to use the argument `--save ""`
