### ISSUE TITLE
set admin (id=1) password if empty

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-manage-service#12]
If the admin's password is `""` or `null`, set the password to a given one. The admin has a fixed id of 1. If the admin does not exists, do nothing (no error case). Please add logs what was done (no admin, admin already had password, password set).

The plan is to change the [initial data](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docker/initial-data.json#L28) to contain no password for the admin. This allows to detect a first-time setup, so the admin password will be set exactly once on the first startup.

This management command should replace [this one](https://github.com/OpenSlides/openslides-manage-service/blob/main/entrypoint-setup#L30). Currently the admin password is reset on every start of the stack.

**Comment by FinnStutzenstein** [comment]
this can be a new command, if you like.

**Comment by ostcar** [comment]
I will do this after #16 is merged. #16 contains some abstractions that I want to use.

**Comment by normanjaeckel** [comment]
Ping.

**Comment by normanjaeckel** [comment]
New proposal: We make a new command that ensures the existance of an admin with password admin.

**Comment by FinnStutzenstein** [comment]
If the admin was deleted, we do not want to recreate the admin on every startup.

**Comment by ostcar** [comment]
The Idea is, that you do not run this command on every start, but only when you create the containers for the first time.

**Comment by normanjaeckel** [comment]
The solution in #24 should fix this.

**Comment by ostcar** [comment]
If this is not fixed, please reopen.
