### ISSUE TITLE
implement per-service environment

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#122]
I'll paste the relevant parts from my Mail here (DE):

Problem: Man möchte für einen service neue Umgebungsvariablen setzten, (z.B. EMAIL_HOST, EMAIL_CONNECTION_SECURITY, DEFAULT_FROM_EMAIL)
Um das zu erledigen, ist derzeit die scheinbar einzig sinnvolle Methode diese hart 
(inkl. gesetztem Wert) in ein custom compose-template reinzuschreiben, etwa:

```
  {{- with .Services.backend }}

  backend:
    image: {{ .ContainerRegistry }}/openslides-backend:{{ .Tag }}
    [...]
    environment:
      << : *default-environment
      EMAIL_HOST: mail.example.com
      EMAIL_CONNECTION_SECURITY: "STARTTLS"
      DEFAULT_FROM_EMAIL: noreply@example.com
    [...]

  {{- end }}
```

Eine Möglichkeit wäre jetzt gewesen, das defaultEnvironment dafür anzupassen. 
Das ist jedoch unschön, da diese sehr service-sepzifischen Variablen in die 
anderen wirklich nicht mit eingebunden werden müssen.
Ein weiterer Nachteil: Wenn das defaultEnvironment sich ändert müssen, um es 
anzuwenden, *alle* services neugestartet werden (da sich für alle das env 
ändert). Auch wenn wir eigentlich wissen, dass eigentlich nur - z.B. das 
backend - neugestartet werden muss.

Daher mein Vorschlag, den ich auch für eine logische und flexible Erweiterung 
halte: In der config.yml Datei ein `services.<service>.environment` tag 
einbauen und dies wiederum unter mehreren mergen.
Eine toplevel config Datei könnte dann so aussehen:
```
[...]
services:
  backend:
    environment:
      EMAIL_HOST: mail.example.org
      EMAIL_CONNECTION_SECURITY: "STARTTLS"
      DEFAULT_FROM_EMAIL: noreply@example.com
```

Die zweite - spezifische - Datei z.B. so:
```
[...]
services:
  backend:
    environment:
      EMAIL_HOST: mail.customerxyz.com
```

Das template ungefähr so (am Bsp. backend):
```
  {{- with .Services.backend }}

  backend:
    image: {{ .ContainerRegistry }}/openslides-backend:{{ .Tag }}
    [...]
    environment:
      << : *default-environment
      {{ .Environment }}
  [...]
  {{- end }}
```

Die resultierende compose.yml, täte ich dann so erwarten:
```
[...]
  backend:
    [...]
    environment:
      << : *default-environment
      EMAIL_HOST: mail.customerxyz.com
      EMAIL_CONNECTION_SECURITY: "STARTTLS"
      DEFAULT_FROM_EMAIL: noreply@example.com
    [...]
[...]
```

Das würde es uns deutlich vereinfachen spezifische Konfiguration vorzunehmen.

Außerdem sehe ich, dass es bereits einige service spezifische variablen gibt 
(z.B. vote.{MESSAGING,AUTH}, datastore-reader.NUM_WORKERS, etc.), die aktuell 
hart im template gesetzt werden und nur schwierig anpassbar sind.
Diese würden dann stattdessen in der `pkg/config/default-config.yml` angegeben 
werden und können bei Bedarf vom Nutzer überschrieben werden.
Das Überschreiben sollte wie gewohnt kaskadieren, sodass - in 'später' 
angegebenen config files definierte - keys bereits vorhandene im 
per-sevice-environment überschreiben.

Ein weiterer Vorteil, den ich mir von dem Feature verspreche:
Wie ich das verstehe kann ich keine beliebige neue Variable im 
defaultEnvironment angeben, da im template nur die erwarteten keys explizit 
ausgelesen werden.
`services.<service>.environment` sollte stattdessen generisch behandelt werden 
und über jeden angegebenen key iterieren und der YAML-Struktur hinzufügen.
Auf diese Weise müssen wir auch nicht für jede neue Variable, die wir mal 
anpassen wollen, eine neue Version des manage-tools haben.

appreciate your efforts :)

**Comment by normanjaeckel** [comment]
Should be done.
