### ISSUE TITLE
Fails when HTTPS support is disabled

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#126]
The latest version of `openslides` appears to be unable to connect to the management service when HTTPS support is disabled in the proxy.

To reproduce:
```
openslides setup .
sed -i '/ENABLE_LOCAL_HTTPS/d' docker-compose.yml
docker-compose up -d
openslides initial-data
```

This might be the explanation for the problem reported in https://github.com/OpenSlides/openslides-manage-service/pull/114.  I'm opening a new issue because that PR has been merged in the meantime.

If the HTTPS setting is, in fact, the culprit, I would recommend to add it to your test routine permanently.

**Comment by peb-adr** [comment]
Oh nice observation!
I can confirm to this that the issue started with [this commit](https://github.com/OpenSlides/openslides-manage-service/commit/16ad83cb13d18588fdb743e099a059a028eac88c#diff-6aeec4039e513e7673357d54b4948df8bd7858708e1d0a5af1574b64aae49eceL84)
Undoing the TLS related change in `connection.go` fixes the problem in our setup.
