### ISSUE TITLE
SSL certs should only be generated if `enableLocalHTTPS: true`

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#129]
currently it looks like `openslides setup` will always generate local ssl certs for HTTPS.
It should instead respect the `enableLocalHTTPS` config, so systems that use their own HTTPS setup wont be unnecessarily cluttered.

I imagined this is just a matter of adding an appropriate if statement in `setup.go`.
However looking at it seems `setup.go` doesn't yet parse the config file (only `config.go` does).
So I think some refactoring would be in order to call `newYmlConfig()` from `setup.go`.

**Comment by normanjaeckel** [comment]
@peb-adr This issue should be solved, right?

**Comment by peb-adr** [comment]
yes
