### ISSUE TITLE
Add `ALLOWED_HOSTS` env variable

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#134]
It must be possible to configure the reverse proxy's [`ALLOWED_HOSTS`](https://github.com/OpenSlides/OpenSlides/pull/6315) environment variable through custom `config.yml` files.

This is the equivalent OpenSlides 3 setting: https://github.com/OpenSlides/OpenSlides/blob/1e22ffbf7e4e2d9f410bca0d1eca14e3b7642d05/docker/.env#L37-L41

Instead of specifically adding this one variable, this may also be an opportunity to discuss/implement https://github.com/OpenSlides/openslides-manage-service/issues/122 instead.

**Comment by normanjaeckel** [comment]
See #137

**Comment by normanjaeckel** [comment]
Should be done.
