### ISSUE TITLE
`create-user`: Specify user IDs

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#135]
Would it be possible to extend the `create-user` function to accept specific user IDs?  It should refuse to add a new user if the given ID already exists.

This would allow us to safely re-run `create-user` on every instance start just like it is safe to run `initial-data` repeatedly.

It is also how OpenSlides 3 worked: https://github.com/OpenSlides/OpenSlides/blob/1e22ffbf7e4e2d9f410bca0d1eca14e3b7642d05/server/docker/entrypoint-db-setup#L66-L76

**Comment by normanjaeckel** [comment]
The backend does not accept user ids, see https://github.com/OpenSlides/OpenSlides/wiki/user.create.
I propose to use unique usernames. It should be save to run the create user command with the same username twice. You should get an error in the second run. Can you please test this?

**Comment by gsiv** [comment]
> You should get an error in the second run.

That's correct; however, my concern was that an admin unaware of how the user setup process works might edit an existing user setup YAML file, thereby accidentally causing a new user to be added.  So, on its own, the unique username check not a complete solution.

If the simple user ID method is not an option, we can solve this another way though.  I'll close this issue.
