### ISSUE TITLE
Build openslides tool for different architectures

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#138]
currently the github action hook build `openslides` executable only for linux.
As discussed, we should add targets to build for other architectures, namely Mac, Windows (more?)

**Comment by alveolus** [comment]
> We can use https://goreleaser.com/ for this.

@normanjaeckel Any news on this matter? :)

**Comment by normanjaeckel** [comment]
This is still a TODO.

**Comment by normanjaeckel** [comment]
Duplicate to #30
