### ISSUE TITLE
Create backups with pgdump

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-manage-service#143]

**Comment by normanjaeckel** [comment]
@ostcar Do you have any proposal for me here?

Where should the pg_dump utility live? Should I copy such a binary into the manage service and then go from manage tool via a new gRPC route to the service and the call the pg_dump binary? I know that this binary is already present in the postgres container but I do not know how to go from the manage service into this container.

**Comment by ostcar** [comment]
I think the nicest thing would be to a go implementation for pg_dump. So you could use the normal postgres-server to create the dump without the need to provide a copy of pg_dump. There is this package, that I have not tested: https://pkg.go.dev/github.com/habx/pg-commands#section-readme maybe there are more packages that can help with that task. Since this is a backup, we have to be sure, that it works. So maybe this is to critical for a self written tool.

The alternative is to provide the pb_dump binary with all it dependencies. This will probably increase the size of the manage-tool-binary multiple times.

I also don't know how to access the postgres container from the management contain without mountin the docker socket into the manage container. But even if this is possible, I don't think, that this is a good idea. The postgres-container is not mandatory. You can use an external postgres-server (Intervation does this). So a backup solution, what requires a postgres container could not be used all the time.

**Comment by normanjaeckel** [comment]
Looks like that the package is just a Go wrapper around an existing pg_dump binary.

**Comment by normanjaeckel** [comment]
I think I can not use the exec interface from inside the manage container. The manage container does only contain the go binary and nothing else at the moment ...

**Comment by funkyfuture** [comment]
ah, sorry, i thought that the `openslides` binary shall invoke the backup tasks.

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/OpenSlides/pull/6533. We decided to promote a solution with docker-compose exec for the moment. If someone has a better solution, her or she is welcome to open a pull request.
