### ISSUE TITLE
Support older versions of docker-compose

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-manage-service#145]
I tried to install openslides on ubuntu 18.04. 

```
$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
$ $ docker-compose --version
docker-compose version 1.17.1, build unknown
```

When I tried to pull the contains with `docker-compose pull` I got the error message:

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I changed the version number in the compose file from `3.7` to `3.4` (see https://docs.docker.com/compose/release-notes/#1170). Afterwords everything worked without a problem.

The question is: Is there a reason you use the version 3.7? Could you change it to a lower number to support older versions of docker-compose?

**Comment by normanjaeckel** [comment]
Looks like that we can change it to `3.4`. I can not test this but if you say, that `3.4` works fine, it is ok for me. Versions 3.3 or lower won't work because we use [extension fields](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) which were introduced in `3.4`
