### ISSUE TITLE
Document mail setup

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-manage-service#149]
This is probably the wrong repo for this issue. But I did not know where else to repot it.

I installed a OpenSlides4 instanz with docker-compose on my server. Everything looks good. But when I try to reset my password, I get an error message, that the server is not configured correctly. The backend logs:

```
backend_1          | General send mail exception: [Errno -3] Temporary failure in name resolution
```

Can someone explain to me, and maybe document somewhere, what I have to do to setup mails? 

I have a running mailserver on outside the docker-compose network.

**Comment by ostcar** [comment]
Thank you very much. This worked.

In my case, it was not necessary to set the `uplink` setting. It seems, that in docker-compose, each host can access the internet.

I only had to set `EMAIL_HOST`. All other settings seems to be working with there default values. I also set `DEFAULT_FROM_EMAIL`, but I don't think, this is necessary.

@normanjaeckel Maybe this should be explained in the readme?

**Comment by normanjaeckel** [comment]
Sure, I can do this

**Comment by neferin12** [comment]
> In my case, it was not necessary to set the uplink setting. It seems, that in docker-compose, each host can access the internet.

In my case it was indeed necessary to set that setting, so it might be a good idea to also add it to the documentation

**Comment by normanjaeckel** [comment]
@ostcar @peb-adr @gsiv Can someone of you verify whether it is necessary to add the backend to the uplink network. At the moment the backend is only in the frontend and in the data network so it can only be reached via the proxy.

**Comment by ostcar** [comment]
Only Caddy should be in the Uplink network. Can you explain why you think it is necessary for mail support to change this?

**Comment by neferin12** [comment]
Trial and error. I could not get emails to work, when I tried sending one by using "forget password" or sending invitations, it failed with the message `[Errno 99] Cannot assign requested address` in the logs. As soon as I added the `uplink` network to `backend` it worked (and that was the only thing that I changed).

FYI:
Docker version 20.10.14
Docker Compose version v2.2.3

**Comment by ostcar** [comment]
You are right. I misunderstood the flag "internal" in the docker-compose-file. This is strange, because it worked for me. Maybe I have an older compose-version that ignores the internal flag?

How do we solve this? I do not like to add the backend to the upstream repo. Do we need some sort of mail proxy? @peb-adr what do you think?

**Comment by ditschi** [comment]
I also can confirm this ... After adding `uplink` network to `backend` it worked  for me aswell

I use the default v4 compose but deactivated https in the proxy. That way I can use may existing traefik setup to do the https by adding the traefik configuration using  labels

**Comment by normanjaeckel** [comment]
See #205
