### ISSUE TITLE
Make instance's public URL available to backend

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#150]
The backend service needs to know its own public URL, that is, the URL at which users can access the instance.  It is at least going to be used for the backend's `users_pdf_url` setting.

The URL should probably be added as an environment variable like in OpenSlides 3, cf. https://github.com/OpenSlides/OpenSlides/blob/fceb892005b9fe1689b00679c754aeb4f74f0f66/docker/docker-compose.yml.m4#L93-L94.  We called it `INSTANCE_DOMAIN` there.  Due to the usage of the term "instance" within OpenSlides 4, something like `SYSTEM_URL` might be more appropriate here.

There are other options that we can discuss, such as configuring the setting directly in the database through the management tool; however, it is my understanding that the backend developers are expecting a variable at the moment.

**Comment by normanjaeckel** [comment]
Let's add `SYSTEM_URL`. This is pretty easy.
