### ISSUE TITLE
Extend `set` + rework `create` (?)

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#181]
For the set command i realized it currently supports updating organization and meeting fields.
For scripting automated instance-create it would be good to have a committee be settable as well.
This might just be a one-line code change, if extending `pkg/set/set.go:29 actionMap` is actually enough.

Also a bigger part of this issue:
I think the `create` command should be reworked. Right now we only have the specific create-user command.
If `create` worked analogous to `set` it would be more consistent and expandable.
That is the collection of which a new object has to be created should be passed as an argument.
E.g. `openslides create user -f user.yml`, `openslides create meeting -f meeting.yml` etc.

And then `create` would have it's own supported `actionMap`, which should contain: `["committee", "meeting", "user"]`

**Comment by normanjaeckel** [comment]
Discussed with @peb-adr  and @m-schieder : Lets create a new `action` command for arbitrary actions using a `--fields` flag, a `--raw` flag for raw JSON or `--file`.

Then the `set` command has a mapping to all update actions like `organization.update` but not for all of them.

**Comment by peb-adr** [comment]
list of included collections:

"agenda_item": "agenda_item.update",
"committee": "committee.update",
"group": "group.update",
"meeting": "meeting.update",
"motion": "motion.update",
"organization_tag": "organization_tag.update",
"organization": "organization.update",
"projector": "projector.update",
"theme": "theme.update",
"topic": "topic.update",
"user": "user.update",

**Comment by normanjaeckel** [comment]
Should be done with #204
