### ISSUE TITLE
Add support for traefik / generic customization of the `docker-compose.yml`

### ISSUE THREAD

**Issue by funkyfuture** [OpenSlides/openslides-manage-service#186]
hello, i'm tasked with the evaluation of hosting an OpenSlides instance which inevitably means using this tool.

it seems that one shouldn't edit the generated `docker-compose.yml` directly as it can be regenerated with `openslides`.

as we're using [traefik](https://doc.traefik.io/traefik/) as reverse proxy for Docker based deployments of web applications, we'd need to amend labels to the `proxy` service and define the `uplink` network in the `docker-compose.yml`. it would thus be desirable to define these in the configuration file that can be passed to `openslides`.

for the labels section that is no problem with the available facilities, but defining the network isn't supported or not documented.

(btw, i don't see the point in a default configuration that listens on `127.0.0.1` and is secured with TLS. also my strong opinion is that transport security is of no concern for an application.)

**Comment by gsiv** [comment]
> as we're using [traefik](https://doc.traefik.io/traefik/) as reverse proxy for Docker based deployments of web applications, we'd need to amend labels to the `proxy` service and define the `uplink` network in the `docker-compose.yml`.

For a single instance, you might be able to achieve that with custom templates that contain the necessary changes.  Additionally, and especially if you're planning to run multiple instances, you may want to have a look at https://github.com/OpenSlides/openslides-hosting-tools/.

**Comment by funkyfuture** [comment]
> you might be able to achieve that with custom templates that contain the necessary changes.

which template do i have to edit in order to change this snippet from the `docker-compose.yml`

```yaml
networks:
  uplink:
```

to

```yaml
networks:
  uplink:
    external:
      name: <name>
```

?

> if you're planning to run multiple instances, you may want to have a look at

no, that doesn't seem useful for us as we have a reverse proxy for all web services in place and are using one of the common orchestration tools for deployments.

**Comment by normanjaeckel** [comment]
The question for me would be whether we need an extra option for custom network settings and how this should look like. Implemention such option would be ok for me (although we should not forget that we do not want to rebuild the whole power of Compose config ...).

**Comment by normanjaeckel** [comment]
We have a config.yml to customize the generation of our docker-compose.yml. The idea is that most users can just use the default or can change some properties in the config.yml to get a customized docker-compose.yml. My intention was not to create a tool that enables all features of Compose via our config.yml. E. g. if someone customizes a single service and also wants to use new secrets this a really rare case. Such a user has to change the docker-compose.yml by hand or use a customized template. In others word: I only want to add features to our docker-compose.yml-generation-process if such a feature helps more than just one single usecase.

**Comment by normanjaeckel** [comment]
Please reopen if there is anything left here.
