### ISSUE TITLE
docker-compose.yml invalid after "./openslides setup ."

### ISSUE THREAD

**Issue by Backfisch145** [OpenSlides/openslides-manage-service#193]
After following all the installation setps, i could not pull/up the compose file.

I was getting the following Error:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.postgres.user contains an invalid type, it should be a string`

~~To fix that issue, you have to manualy edit the docekr-compose.yml and remove the "---" at the top of the File.~~

**Comment by normanjaeckel** [comment]
The error message does not fit to your solution. The `---` is a [YAML document marker](https://yaml.org/spec/1.2.2/#document-markers) and has (hopefully) nothing to do with the content of the Compose file. Maybe there was another problem in your file and/or your are using an old Compose version or whatever. Maybe your operating system does not fully support what we are doing [here](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/config/config.go#L232). In this case it would be interesting how to solve the problem.

If necessary please post your Compose file. Thanks.

**Comment by Backfisch145** [comment]
As you said, the `---` were not the cause, I edited my initial issue.

System OS:
`Distributor ID: Debian 
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster`

Docker Version:
`Docker version 20.10.18, build b40c2f6`
docker-compose:
`docker-compose version 1.29.2, build 5becea4c`

1. wget https://github.com/OpenSlides/openslides-manage-service/releases/download/latest/openslides
2. chmod +x openslides
3. ./openslides setup .
4. docker-compose pull
5. `ERROR: The Compose file './docker-compose.yml' is invalid because:...`

Here is my generated yml:
[docker-compose.yml.txt](https://github.com/OpenSlides/openslides-manage-service/files/9693282/docker-compose.yml.txt)

**Comment by normanjaeckel** [comment]
I just generated the file myself and the only difference is in line 184 `    user: 1000:985`. Here you have `user: 1000:0` which should also work without problems.

Please try to set the user and group id into quotes. `user: "1000:0"` and let us know if this works.

**Comment by Backfisch145** [comment]
Putting the user id and group into quotes, fixed the problem.

**Comment by normanjaeckel** [comment]
We should change the code so that user id and group id are always quoted so there is no need to change things manually.

**Comment by funkyfuture** [comment]
in #188 i argued that configuring the database's process user in such way isn't portable at all. the proposed fix is marked with the 4.0 milestone and would render this issue as invalid / solved depending on how you sort the world).

**Comment by normanjaeckel** [comment]
#188 is merged so the problem does not exist any more.
