### ISSUE TITLE
"Create meeting" button does not work

### ISSUE THREAD

**Issue by GoblinMage** [OpenSlides/openslides-manage-service#197]
As written in the title, since the past 3 days, the "+"-button to create a new meeting within a committee does not work. Docker-logs aren't  giving out any indicators or pointers, that there has been an error or even an attempt to start the action.

The "import meeting"-Button also stopped working.

By now I have rebuild my whole Openslides-Setup several times with no changes to show. Is there something broken with my installation? Is this a known issue? I can't seem to find other people on here with the same problem.

**Comment by normanjaeckel** [comment]
I just tested a brand new installation without any issues. Please reopen if the problem still occurs.
