### ISSUE TITLE
Upgrade Postgres

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-manage-service#213]
This service uses postgres:11 for the postgres container. But in production, we are using postgres:13.

Since postgres:11 will only be [supported until November 9, 2023](https://www.postgresql.org/support/versioning/) we need to think about an update strategy. 

This should be done before the 4.1 release.

**Comment by ostcar** [comment]
@normanjaeckel we discussed, that a message in the release notes with a link to the postgres page should be enough.

Could you change the postgres version? (And remember this for the release notes?)

**Comment by ostcar** [comment]
@peb-adr Could you have a look at this?

**Comment by ostcar** [comment]
Postgres 11 is not supported anymore

**Comment by peb-adr** [comment]
Closed by #235 and will be included with version 4.1
We will provide short instructions on how to handle this update.
