### ISSUE TITLE
Compatibility with Go 1.15

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#48]
If I'm not mistaken, this tool requires Go 1.16 to compile.  That version isn't even going to be included in the *next* Debian release: https://packages.debian.org/bullseye/golang

Could it be made to work with Go 1.15?

**Comment by ostcar** [comment]
Why do you have to compile the tool? We provide binaries that run on every distro.

**Comment by gsiv** [comment]
> Why do you have to compile the tool? We provide binaries that run on every distro.

Come on...

Here is *one* reason: I may want to edit the included template until issue #45 is resolved.

**Comment by ostcar** [comment]
So lets solve #45 :)

**Comment by gsiv** [comment]
Okay, I'll interpret that as “no, it would be hard to make it work with Go 1.15” in which case I’ll agree with you.
