### ISSUE TITLE
admin secrets does not exist

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-manage-service#56]
old 'admin' secrets has to rename to 'superadmin' in docker-compose.yml.tpl otherwise you get this error during start docker-compose up:

``
ERROR: for manage  Cannot create container for service manage: invalid mount config for type "bind": bind source path does not exist: /srv/openslides/os4-instances/demo/secrets/admin
``

**Comment by emanuelschuetze** [comment]
And please add "postgres" as "networks" to backend section in docker-compose.yml.tpl. Thanks.

**Comment by normanjaeckel** [comment]
Should be fixed with #57. Please reopen if something is left.
