### ISSUE TITLE
[meta] Migrations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-manage-service#61]
- [x] Implement #59
~~- [ ] Get the current `initial-data.json`. It should have a `_migration_index` of 1.~~
- [x] Based on #59 Implement #58 and send the migration index on the single write request to the datastore.
- [x] Fix #60

If this is all done:
- [ ] Speak with Gernot and Adrian: Integrate migrations as described in my email.

**Comment by normanjaeckel** [comment]
Initial-data.json has now migration_index 3 so the initial data do not have to be migrated.
