### ISSUE TITLE
set password and first login

### ISSUE THREAD

**Issue by kempert** [OpenSlides/openslides-manage-service#69]
I can not set the passwort for the user admin to first login. 

./openslides set-password -u 1 -p "admin"
Error: connecting to gRPC server: creating gRPC client connection with grpc.DialContect(): context deadline exceeded

how are the standart user data. What i can do to know the password?

**Comment by refda** [comment]
Hey, I still have the same error. I hope it can be fixed soon. I am not able to insert the initial data and I have no credentials to login...

**Comment by normanjaeckel** [comment]
You have to run docker-compose up frist. Can you please check, if the respective port (e. g. localhost:9008) is open?

The default password is found in the secrets directory. The first user is called "superadmin" and has the password "superadmin". We changed the name and the password recently.
