### ISSUE TITLE
Offline-Mode when opening a meeting

### ISSUE THREAD

**Issue by tanjix** [OpenSlides/openslides-manage-service#76]
Hi Guys,

I recently installed the latest version of Openslides v4 with docker-compose and got it running, including the initial-data setup.
Logging in works fine as well as modifying the commitee and adding members.
Even modifying the default meeting works fine and entered values are stored to the database. So far, all fine.

Now, when opening the meeting, after a few moments, a blue bar is showing up and saying "offline mode", with the effect, that no agenda items, motions etc. can be stored. Although I can open the "add agenda" page and enter my values, it doesn't save them. I am being returned to the agends overview page (with no new item that I tried to save). From this point on, no other page cannot be opened any more when clicking around, regardless, which one (agenda, motions, elections, ...).

Don't know, which kind of technical excerpts/logs I could provide to help troubleshooting.
However, I've tried it on two different servers with two fresh installations, so I assume it to be a global issue.

Thanks a lot!

**Comment by ostcar** [comment]
Do you use http or Https?

For some reasons, only Https is supported but there is no nice error message on http connections.

**Comment by tanjix** [comment]
Hi @ostcar, I am using it with http, indeed; didn't manage yet to find out, how to enable SSL on the setup using the openslides-manage-service and docker-compose, which does the overall setup automatically.

However, if using https solves the issue for the time being, could you provide a short tutorial, on how to enable it? I found issue #46 but where do I need to go, to do it?

Thanks!

**Comment by ostcar** [comment]
We are currently working on the https setup. But you will probably need a domain. So it will probably not be possible to use openslides4 on localhost. Maybe we could document a way to create valid certificates for localhost with [mkcert](https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/)

**Comment by tanjix** [comment]
Using a (sub)domain is not an issue. So, whatever I could do for the moment, I'd be happy to get an info on. Thank you!

**Comment by ostcar** [comment]
This is the branch, where this feature is implemented currently: https://github.com/OpenSlides/OpenSlides/compare/master...peb-adr:proxy-rework

**Comment by tanjix** [comment]
I am an end-user only with basic knowledge in docker. To get this to work and after having read this:

## Automatic HTTPS

It is possible to make use of caddy's automatic https feature in order to not
having to manually generete TLS certificates.
Set `ENABLE_AUTO_HTTPS=1` and `EXTERNAL_ADDRESS=openslides.example.com` to
activate it. Caddy will then retrieve a letsencrypt certificate for that
domain.

Is this something I'd need to add to docker-compose.yml and then do the "docker-compose up -d" again?

Thanks!

**Comment by peb-adr** [comment]
It's not a https problem. Rather a connectivity issue between proxy and icc.
For now the workaround seems to be adding the `uplink` network to the icc service in the docker-compose.yml
@tanjix u might wanna try that.
It will be fixed by default eventually as well

**Comment by tanjix** [comment]
Hi Guys! I gladly tested that by adding the uplink network as suggested.
Now, when I try to add or modfiy a meeting, I get a popup on the page footer: "The server didn't respond", which I can confirm with clicking OK. Changes are not saved.

**Comment by normanjaeckel** [comment]
We changed a lot of things in the OpenSlides 4 stack the last weeks. I will close this but do not hesitate to reopen the issue (or open an new one) if you have any problems with the current state.
