### ISSUE TITLE
add migrations subcommand

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#77]
As discussed, we are currently envisioning a call from the manage-service to the backend to initiate pending migrations.
@jsangmeister will implement an HTTP-route the backend to wrap the internal `migrate.py` script.
This will be somewhat of the form `/system/migrations`.
The body of a request to that should be a json object of the form `{ "cmd": "migrate" | "finalize" | "stats" | "reset" | "clear-collectionfield-tables", "flags": ["verbose"] }` (flags can also be an empty list)
corresponding to the subcommands of `migrate.py` (see https://github.com/OpenSlides/openslides-backend/blob/master/migrations/migrate.py).
The `openslides` command should in turn provide these to the user

So as an example a user would want to check if migrations are needed, so they could:
`./openslides migrations stats --verbose`
which sends an grpc call to manage-server -> manage-server sends HTTP request with body `{ "cmd": "stats", "flags": "verbose" }` to `backend/system/migrations` -> HTTP response will include `manage.py`'s answer which can be relayed back to the user.

Similarly the user could call
`./openslides migrations migrate`
`./openslides migrations finalize`
`./openslides migrations reset`
`./openslides migrations clear-collectionfield-tables`

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend/pull/921

**Comment by normanjaeckel** [comment]
Migration route exists in backend and can be used now. Still open: Do we change the handling with kind of long polling or repeated requests if backend is very slow.

**Comment by peb-adr** [comment]
@normanjaeckel 
It would be great if you could get to this too in the near future.
Are there open questions still?

> Migration route exists in backend and can be used now. Still open: Do we change the handling with kind of long polling or repeated requests if backend is very slow.

I'm not too sure what this was about exactly, but the manage service will have to do repeated requests on the progress of the running migration.

I will provide you our current script in use to run `migrations/finalize` for an updated instance,
I hope this will help you figure out what the requests to the `backendManage' need to look like.

Also https://github.com/OpenSlides/openslides-backend/pull/1076#issuecomment-984645837 will probably be helpful on how the `/migrations` route works.
