### ISSUE TITLE
possibility to rebuild compose.yml without regenerating secrets

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#78]
It should be possible to update the config of a running instance and redeploy it without taking it down completely.

I observed the following working with `./openslides` from the Templating branch.
I have an instance running (using swarm in my case). Then i change some env var in `config.yml`.
To reflect these changes into the `docker-compose.yml`, seems to me i have to run `./openslides setup . --config config.yml --force`. Without `--force` it would refuse to overwrite existing files.
However now the secrets have been regenerated as well which is not feasible.

So one way of doing this i think would be:
have a seperate command (e.g. `./openslides config`) for handling the compose-file wich will also implicitly be called by `./openslides setup`

Another (for now) simpler way:
Add a flag named something like `./openslides setup --reload-config` which would only recompile the compose-file.
However I think my first proposal would be cleaner code.

@ostcar @normanjaeckel opinions on this?

**Comment by normanjaeckel** [comment]
Ok, I can do it the first way. I will update the Templating branch directly.

**Comment by normanjaeckel** [comment]
Implemented in #74 .

**Comment by normanjaeckel** [comment]
Should be done with #74
