### ISSUE TITLE
Store database credentials in Docker secrets

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#83]
With the current template, the variables `DATASTORE_DATABASE_HOST`, `DATASTORE_DATABASE_PASSWORD`, `MEDIA_DATABASE_HOST` and `MEDIA_DATABASE_PASSWORD` all get added to `x-default-environment` in docker-compose.yml.  Thereby, they are being unnecessarily exposed to all services.  Instead, they should be contained in Docker secrets.

I have opened issues with the respective services:

  * datastore: https://github.com/OpenSlides/openslides-datastore-service/issues/152
  * media: https://github.com/OpenSlides/openslides-media-service/issues/27

Please also see Issue https://github.com/OpenSlides/openslides-manage-service/issues/82.

**Comment by peb-adr** [comment]
The backend also relies on the DATASTORE_DATABASE_* variables so i think there should be an issue for it as well.
The other services seem to be fine.

**Comment by normanjaeckel** [comment]
Should be done.
