### ISSUE TITLE
Do not create db-data directory if the Postgres services is disabled

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#85]
Setting `disablePostgres: true` disables the Postgres service in the generated YAML file.  The setup command should avoid creating the `db-data` directory in this case.

**Comment by funkyfuture** [comment]
excuse me for being slightly off-topic: why is this folder exposed on the host's filesystem anyway? shall i create a separate issue with this question?

**Comment by normanjaeckel** [comment]
Folder is removed by #188
