### ISSUE TITLE
CLI command for adding additional user accounts

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#88]
We need a way to programmatically add additional users.  Furthermore, it must be possible to query the added users' information:

  * username
  * full name
  * email address
  * initial password

For our specific use case, we actually only need to be able to add exactly one administrative user account.  For this purpose, the method employed by OpenSlides 3 (see below) would still work perfectly well.  Since that way the user information is available in a `secrets` file, it remains available even while the instance is not running which is an advantage.

I imagine you might want to add a generic `adduser` command instead, however, e.g., `openslides adduser --role=admin --name="John Doe" --email=john@example.com john` or something like that.  That would generally be okay, too, of course.  The password should be generated; an option to interactively ask for the password wouldn't hurt but is not strictly necessary, in my opinion.

For your convenience, this is the OpenSlides 3 setup:

  * template:

    * https://github.com/OpenSlides/OpenSlides/blob/bbdbdd3c10199485afaeedc94f3911331c57a082/docker/docker-compose.yml.m4#L44
    * https://github.com/OpenSlides/OpenSlides/blob/bbdbdd3c10199485afaeedc94f3911331c57a082/docker/docker-compose.yml.m4#L161
    * https://github.com/OpenSlides/OpenSlides/blob/bbdbdd3c10199485afaeedc94f3911331c57a082/docker/docker-compose.yml.m4#L286-L287

  * back end (presumably replaced by the manage service in OS4):

    * https://github.com/OpenSlides/OpenSlides/blob/bbdbdd3c10199485afaeedc94f3911331c57a082/server/docker/entrypoint-db-setup#L57-L80

**Comment by GabrielInTheWorld** [comment]
I don't like it to perform actions without an authentication. 
You can do this to achieve your goal:

- Prompt a user to enter their username and password
- Send a request to the auth's login-route
- Store the returning token and cookie

Then, the user can perform actions by your tool without any modification of the infrastructure of our application.

**Comment by normanjaeckel** [comment]
Internal route exists so this has to be done now.

**Comment by normanjaeckel** [comment]
Should be done.
