### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by christi1705** [OpenSlides/openslides-manage-service#99]
Can't reach the webpage with the current version.

It's no problem to reach the side with "wget localhost:8000", but I get an ERR_CONNECTION_REFUSED while trying to "wget <external-IP>:8000"

Someone else facing that problem? Any fix?

**Comment by normanjaeckel** [comment]
Do you use an extra proxy to provide HTTPS support? OpenSlides needs to be used with HTTPS but at the moment we do not have a build in support. Maybe you have to setup a proxy in front of OpenSlides with respective certificates. See https://github.com/OpenSlides/openslides-manage-service/issues/46

**Comment by normanjaeckel** [comment]
The current stack should be fine now. Please reopen if there are any issues.
